"""add_users_and_token_blocklist

Revision ID: 603587739639
Revises: 79ea49673d09
Create Date: 2026-07-12 15:45:56.152545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603587739639'
down_revision: Union[str, Sequence[str], None] = '79ea49673d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # batch_alter_table: en PostgreSQL equivale a un ALTER TABLE normal, pero en
    # SQLite (que no soporta agregar constraints con ALTER) recrea la tabla.
    with op.batch_alter_table('events') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_events_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('files') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_files_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('songs') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_songs_user_id_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs') as batch_op:
        batch_op.drop_constraint('fk_songs_user_id_users', 'songs', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('files') as batch_op:
        batch_op.drop_constraint('fk_files_user_id_users', 'files', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('events') as batch_op:
        batch_op.drop_constraint('fk_events_user_id_users', 'events', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
