"""add guests and custom budget fields

Revision ID: 7fcf5cd90f2a
Revises: 4604663eafc1
Create Date: 2026-07-01 16:08:12.763255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcf5cd90f2a'
down_revision: Union[str, Sequence[str], None] = '4604663eafc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('guests_count', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('estimated_logistic_budget', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'estimated_logistic_budget')
    op.drop_column('events', 'guests_count')
    # ### end Alembic commands ###
