"""tablas base y repertoriosasdsa

Revision ID: 99e94731d651
Revises: 7fcf5cd90f2a
Create Date: 2026-07-11 12:35:07.640197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e94731d651'
down_revision: Union[str, Sequence[str], None] = '7fcf5cd90f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logistics_to_bring', sa.JSON(), nullable=True),
    sa.Column('monetary_contribution', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('contribution_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('logistics_to_bring', sa.JSON(), nullable=True),
    sa.Column('monetary_contribution', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('contribution_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['participant_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    op.drop_table('participant_groups')
    # ### end Alembic commands ###
